name: services_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  firebase_core: ^1.24.0
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.10.0 
  flutter_svg: ^1.1.5
  image_picker: ^0.8.6
  form_builder_image_picker: ^3.1.0
  geolocator: ^9.0.2
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^9.2.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.11
 

 
    

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.10+1
  flutter_launcher_icons: ^0.10.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/imgApp.png 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgApp.png"
  adaptive_icon_foreground: "assets/icon_forground.png"   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/icons/vehicule.png
    # - assets/icons/domestic.png
    # - assets/icons/bus.png
    # - assets/icons/admin2.png
    # - assets/icons/besoin2.png
    # - assets/icons/car-rental.png
    # - assets/icons/maison2.png
    # - assets/icons/trumpet.png
    # - assets/icons/transport.png
    # - assets/icons/pneu.png
    # - assets/icons/carburant.png
    # - assets/icons/car-battery.png
    # - assets/icons/remorquage.png
    # - assets/icons/assurance2.png
    # - assets/icons/nettoyage.png
    # - assets/icons/chauffeur.png
    # - assets/icons/gardian2.png
    # - assets/icons/houseEmployee2.jpg
    # - assets/icons/femmeMenage2.png
    # - assets/icons/nounou.png
    # - assets/icons/serveur.png
    # - assets/icons/fonce.png
    # - assets/icons/citerneau.png
    # - assets/icons/electricity.png
    # - assets/icons/water2.png
    # - assets/icons/tv.png
    # - assets/icons/paint2.png
    # - assets/icons/menuisier.png
    # - assets/icons/clim.png
    # - assets/icons/addresse.png
    # - assets/icons/category.png
    - assets/icons2/icon1.svg
    - assets/icons2/icon2.svg
    - assets/icons2/icon3.svg
    - assets/icons2/icon4.svg
    - assets/icons2/icon5.svg
    - assets/icons2/icon6.svg
    - assets/icons2/icon7.svg
    - assets/icons2/icon8.svg
    - assets/icons2/icon9.svg
    - assets/icons2/icon10.svg
    - assets/icons2/icon11.svg
    - assets/icons2/icon12.svg
    - assets/icons2/icon13.svg
    - assets/icons2/icon14.svg
    - assets/icons2/icon15.svg
    - assets/icons2/icon16.svg
    - assets/icons2/icon17.svg
    - assets/icons2/icon18.svg
    - assets/icons2/icon19.svg
    - assets/icons2/icon20.svg
    - assets/icons2/icon21.svg
    - assets/icons2/icon22.svg
    - assets/icons2/icon23.svg
    - assets/icons2/icon24.svg
    - assets/icons2/icon25.svg
    - assets/icons2/icon26.svg
    - assets/icons2/icon27.svg
    - assets/icons2/icon28.svg
    - assets/icons2/icon29.svg
    - assets/icons2/icon30.svg
    - assets/icons2/icon31.svg
    - assets/icons2/icon32.svg
    - assets/icons2/icon33.svg
    - assets/icons2/icon34.svg
    - assets/icons2/icon35.svg
    - assets/icons2/icon36.svg
    - assets/icons2/icon37.svg
    - assets/icons2/addresse_svg.svg
    - assets/icons2/category_svg.svg
    - assets/icons2/logout.svg
    - assets/icons2/emptying.svg


   
   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
